### PR TITLE
Remove use of *NIX-specific path strings

### LINKED ISSUE #5: Resolution fails on Windows due to 'absolute path' issuer check
Using yarn in pnp mode, and with the pnp-webpack-plugin installed, the following error occurs on windows:

```
C:\Users\<user>\AppData\Local\Yarn\Cache\v4\npm-pnp-webpack-plugin-1.2.0-a85338bc313b8a0469c1d8c5c5d016873be47cb2\node_modules\pnp-webpack-plugin\index.js:69
        throw new Error(`Cannot successfully resolve this dependency - issuer not supported (${issuer})`);
        ^

Error: Cannot successfully resolve this dependency - issuer not supported (C:\<path_to_my_index.js>)
    ...stacktrace...
```

The line throwing the error, `index.js:69`, is guarded by a a check that the `issuer` string begins with a '/', with a comment that this is checking that the path is absolute. On Windows, this check fails (for obvious reasons).

### PR DESCRIPTION
**Pull request by hWorblehat**
Fixes #5

### CODE REVIEW

**Comment by hWorblehat** [comment]
The Jest tests don't pass for me on Windows without those changes.

Are you sure they work for you on Windows?

Happy to revert them if you insist though...

**Comment by hWorblehat** [comment]
Example (without `path.join`):

```
  ● Regular Plugin › should correctly resolve a relative require

    expect(received).toEqual(expected)

    Expected value to equal:
      "C:\\Users\\<user>\\git\\hWorblehat\\pnp-webpack-plugin/index.js"
    Received:
      "C:\\Users\\<user>\\git\\hWorblehat\\pnp-webpack-plugin\\index.js"

      37 |     const resolution = await makeRequest(resolver, `./index.js`, __dirname);
      38 |
    > 39 |     expect(resolution).toEqual(`${__dirname}/index.js`);
         |                        ^
      40 |   });
      41 |
      42 |   it(`shouldn't prevent the 'extensions' option from working`, async () => {

      at Object.toEqual (index.test.js:39:24)
```

**Comment by arcanis** [comment]
Eh, I see, makes sense ... ``.toEqual(path.normalize(`${__dirname}/index.js`));`` then?

**Comment by hWorblehat** [comment]
Done!

**Comment by arcanis** [comment]
Awesome! Published as 1.2.1 👌

**Pull request merged**
